library(tm)
library(SnowballC)
library(wordcloud)
library(xtable)

google.df <- read.csv('data/book.csv', stringsAsFactors = FALSE)
google.corpus <- Corpus(DataframeSource(data.frame(google.df$content)))
#google.corpus <- tm_map(google.corpus, removePunctuation)
#google.corpus <- tm_map(google.corpus, content_transformer(tolower))
google.corpus <- tm_map(google.corpus, function(x) removeWords(x, stopwords("english")))
tdm <- TermDocumentMatrix(google.corpus)
m <- as.matrix(tdm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
pal <- brewer.pal(9, "BuGn")
pal <- pal[-(1:2)]
#png("wordcloud.png", width=1280,height=800)
wordcloud(d$word,d$freq, scale=c(8,.3),min.freq=2,max.words=100, random.order=T, rot.per=.15, colors=pal, vfont=c("sans serif","plain"))
#dev.off()
